name: Release

on:
  push:
    branches:
      - "docker-buildx"
    tags:
      - "v*.*.*"

permissions:
  contents: write # required for uploading releases

env:
  DEFAULT_GO_VERSION: ^1.16

jobs:
  releaseLinux:
    name: Release Linux
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.DEFAULT_GO_VERSION }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Release Linux Assets
      run: make release
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  releaseWindows:
    name: Release Windows
    runs-on: windows-2019
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.DEFAULT_GO_VERSION }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Release Windows Assets
      run: choco install make && choco install zip && RefreshEnv.cmd && make release-windows
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
